# Generated by Django 3.2.8 on 2021-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='short_desc',
            field=models.CharField(blank=True, max_length=60, verbose_name='краткое описание'),
        ),
    ]
