# Generated by Django 3.2.8 on 2021-10-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_productcategory_short_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
